const coreColor = {
  primary: '#006a68',
  onPrimary: '#ffffff',
  primaryContainer: '#6ff7f4',
  onPrimaryContainer: '#00201f',
  secondary: '#4a6362',
  onSecondary: '#ffffff',
  secondaryContainer: '#cce8e6',
  onSecondaryContainer: '#051f1f',
  tertiary: '#4a607b',
  onTertiary: '#ffffff',
  tertiaryContainer: '#d2e4ff',
  onTertiaryContainer: '#031c35',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#410002',
  outline: '#6f7978',
  background: '#fafdfc',
  onBackground: '#191c1c',
  surface: '#fafdfc',
  onSurface: '#191c1c',
  surfaceVariant: '#dae5e3',
  onSurfaceVariant: '#3f4948',
  inverseSurface: '#2d3131',
  inverseOnSurface: '#eff1f0',
  surfaceDisabled: 'transparent',
  onSurfaceDisabled: 'transparent',
  shadow: 'transparent',
  inversePrimary: 'transparent',
  elevation: {
    level0: 'transparent',
    level1: 'transparent',
    level2: 'transparent',
    level3: 'transparent',
    level4: 'transparent',
    level5: 'transparent',
  },
};

export default coreColor;
